# Generated by Django 3.2.15 on 2022-12-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='recipe',
            name='insructions',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutritions',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.FileField(blank=True, default=' ', upload_to='recipe_photoes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='yields',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
