# Generated by Django 3.2.15 on 2022-12-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221227_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='insructions',
            new_name='instructions',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.TextField(max_length=300),
        ),
    ]
