# Generated by Django 3.2.15 on 2022-12-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221227_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.FileField(blank=True, upload_to='media/recipe_photoes'),
        ),
    ]
